Repository BinaryStudioAcademy/bsa-winter-2021-dbgravy, pull requests merged in 2021-03, with the labels that each got.

#3 add boostrap,formik,react-router,react-router-dom,yup
  frontend/package.json
  frontend/src/common/helpers/historyHelper.ts
  frontend/src/containers/App/App.css
  frontend/src/containers/App/App.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/index.tsx
  frontend/src/scenes/App/App.tsx
Labels: enhancement

#6 Patch/frontend package.json
  frontend/package.json
  frontend/src/index.tsx
Labels: enhancement

#15 Add loader component
  frontend/src/components/Loader/index.tsx
Labels: enhancement

#20 feat(): created org settings page
  frontend/src/common/enums/Routes.ts
  frontend/src/common/enums/UserRoles.ts
  frontend/src/common/enums/UserStatus.ts
  frontend/src/common/models/store/IAppState.ts
  frontend/src/common/models/user/IUser.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/root.ts
  frontend/src/reducers/user.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Settings/components/InviteModal.tsx
  frontend/src/scenes/Settings/components/Sidebar.tsx
  frontend/src/scenes/Settings/components/User.tsx
  frontend/src/scenes/Settings/components/styles.module.scss
  frontend/src/scenes/Settings/containers/Users.tsx
  frontend/src/scenes/Settings/containers/styles.module.scss
  frontend/src/scenes/Settings/index.tsx
  frontend/src/scenes/Settings/reducers/index.tsx
  frontend/src/scenes/Settings/routines/index.tsx
  frontend/src/scenes/Settings/sagas/index.tsx
  frontend/src/scenes/Settings/styles.module.scss
  frontend/src/services/settingsService.tsx
Labels: enhancement

#25 All routes protector
  backend/src/api/middlewares/authorizationMiddleware.ts
  backend/src/api/routes/authRoute.ts
  backend/src/api/routes/index.ts
  backend/src/api/routes/userOrganizationRoute.ts
  backend/src/api/routes/userRoute.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/server.ts
Labels: enhancement

#26 switch organization - backend
  backend/src/api/routes/userRoute.ts
  backend/src/common/helpers/userExtractorHelper.ts
  backend/src/data/repositories/organizationRepository.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/userService.ts
Labels: backend

#28 fix request method
  backend/src/api/routes/userRoute.ts
Labels: bug

#30 Path/token
  backend/src/config/jwtConfig.ts
  backend/src/config/passportConfig.ts
  backend/src/config/routesWhiteListConfig.ts
  frontend/src/common/helpers/apiHelper.ts
  frontend/src/containers/Routing/index.tsx
  frontend/src/scenes/Apps/index.tsx
  frontend/src/scenes/Resources/index.tsx
Labels: bug

#31 Path/routing
  frontend/src/containers/Routing/index.tsx
Labels: bug

#32 Feature/components for apps resources
  backend/src/api/routes/applicationRoute.ts
  backend/src/api/routes/authRoute.ts
  backend/src/api/routes/index.ts
  backend/src/api/routes/resourcesRoute.ts
  backend/src/api/routes/userRoute.ts
  backend/src/common/helpers/appExtractorHelper.ts
  backend/src/common/mappers/resourceExtrator.ts
  backend/src/common/mappers/userOrganization.ts
  backend/src/common/models/application/ITransportedApplication.ts
  backend/src/common/models/resource/ITransportedResource.ts
  backend/src/common/models/userOrganization/IUserOrganization.ts
  backend/src/common/models/userOrganization/IUserOrganizationResponse.ts
  backend/src/data/repositories/resourceRepository.ts
  backend/src/data/repositories/userOrganizationRepository.ts
  backend/src/services/applicationService.ts
  backend/src/services/resourceService.ts
  backend/src/services/userOrganizationService.ts
  frontend/package.json
  frontend/src/common/enums/Routes.ts
  frontend/src/common/models/apps/IApps.ts
  frontend/src/common/models/resources/IResource.ts
  frontend/src/common/models/store/IAppState.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.module.scss
  frontend/src/components/Loader/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/apps.ts
  frontend/src/reducers/resources.ts
  frontend/src/reducers/root.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Apps/components/AddApp/index.tsx
  frontend/src/scenes/Apps/components/AppItem/index.tsx
  frontend/src/scenes/Apps/components/AppItem/styles.module.scss
  frontend/src/scenes/Apps/containers/AppsList/index.tsx
  frontend/src/scenes/Apps/containers/AppsList/styles.module.scss
  frontend/src/scenes/Apps/index.tsx
  frontend/src/scenes/Apps/sagas/index.ts
  frontend/src/scenes/Apps/styles.module.scss
  frontend/src/scenes/Auth/sagas/index.ts
  frontend/src/scenes/Resources/containers/TableContainer/index.tsx
  frontend/src/scenes/Resources/enums/CalendarEnum.ts
  frontend/src/scenes/Resources/enums/TableHeaderEnum.ts
  frontend/src/scenes/Resources/index.tsx
  frontend/src/scenes/Resources/routines/index.ts
  frontend/src/scenes/Resources/sagas/index.ts
  frontend/src/scenes/Routing/index.tsx
  frontend/src/services/applicationService.tsx
  frontend/src/services/resourceService.tsx
Labels: enhancement

#33 Feature/profile popup
  backend/src/api/routes/index.ts
  backend/src/api/routes/organizationRoute.ts
  backend/src/common/models/userOrganization/IOrganizationUser.ts
  backend/src/data/repositories/organizationRepository.ts
  backend/src/data/repositories/userOrganizationRepository.ts
  backend/src/services/organizationService.ts
  backend/src/services/userOrganizationService.ts
  frontend/src/common/models/user/IUser.ts
  frontend/src/common/models/user/IUserOrganization.tsx
  frontend/src/components/CreateOrganization/CreateOrganization.tsx
  frontend/src/components/CreateOrganization/styles.module.scss
  frontend/src/components/Header/index.tsx
  frontend/src/components/Loader/index.tsx
  frontend/src/components/ProfilePopupInfo/ProfilePopupInfo.tsx
  frontend/src/components/ProfilePopupInfo/styles.module.scss
  frontend/src/components/UserAttrButton/UserAttrButton.tsx
  frontend/src/components/UserAttrButton/styles.module.scss
  frontend/src/containers/ProfilePopup/index.tsx
  frontend/src/containers/ProfilePopup/routines.ts
  frontend/src/containers/ProfilePopup/sagas.ts
  frontend/src/containers/ProfilePopup/styles.module.scss
  frontend/src/reducers/user.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Auth/routines/index.ts
  frontend/src/services/userService.tsx
Labels: backend, enhancement

#34 Update relationships
  backend/src/data/entities/RefreshToken.ts
  backend/src/data/entities/User.ts
  backend/src/data/migrations/1615491756693-update-refresh-token-relationships.ts
Labels: bug

#36 Feature/create org with sign in
  backend/src/api/routes/authRoute.ts
  backend/src/api/routes/userOrganizationRoute.ts
  backend/src/common/models/user/IUpdateUser.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/authService.ts
  frontend/src/common/models/auth/IRegisterUser.ts
  frontend/src/scenes/Auth/components/SignIn/index.tsx
  frontend/src/scenes/Auth/components/SignUp/index.tsx
  frontend/src/services/authService.tsx
Labels: backend

#38 Feature/create org with sign in
  backend/src/api/routes/authRoute.ts
  backend/src/api/routes/organizationRoute.ts
  backend/src/common/models/organization/IOrganization.ts
  backend/src/common/models/userOrganization/ICreateUserOrganization.ts
  backend/src/data/repositories/refreshTokenRepository.ts
  backend/src/data/repositories/userOrganizationRepository.ts
  backend/src/services/authService.ts
  backend/src/services/organizationService.ts
  frontend/src/components/ProfilePopupInfo/ProfilePopupInfo.tsx
  frontend/src/containers/ProfilePopup/sagas.ts
  frontend/src/reducers/user.ts
  frontend/src/scenes/Settings/sagas/index.tsx
  frontend/src/services/settingsService.tsx
  frontend/src/services/userService.tsx
  workspace.code-workspace
Labels: bug

#39 Fix/multiple user organization info requests
  backend/src/api/routes/organizationRoute.ts
  backend/src/common/helpers/userExtractorHelper.ts
  backend/src/common/models/user/ITransportedUser.ts
  backend/src/common/models/userOrganization/IOrganizationUser.ts
  backend/src/services/userOrganizationService.ts
  frontend/src/common/models/user/IUser.ts
  frontend/src/common/models/user/IUserOrganization.tsx
  frontend/src/components/ProfilePopupInfo/ProfilePopupInfo.tsx
  frontend/src/components/ProfilePopupInfo/styles.module.scss
  frontend/src/containers/ProfilePopup/index.tsx
  frontend/src/containers/ProfilePopup/sagas.ts
  frontend/src/reducers/user.ts
  frontend/src/scenes/Settings/containers/Users.tsx
  frontend/src/scenes/Settings/sagas/index.tsx
Labels: bug

#40 Display active link in header
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.module.scss
Labels: enhancement

#50 fixed sign-in styles
  frontend/src/index.tsx
  frontend/src/scenes/Auth/components/SignIn/styles.module.scss
  frontend/src/scenes/Auth/components/SignUp/styles.module.scss
  frontend/src/scenes/Auth/containers/index.tsx
  frontend/src/scenes/Auth/containers/style.module.scss
  frontend/src/styles/common.scss
  workspace.code-workspace
Labels: bug

#42 Fix/tokens
  backend/src/api/routes/authRoute.ts
  backend/src/common/helpers/tokenHelper.ts
  backend/src/config/passportConfig.ts
  backend/src/data/repositories/refreshTokenRepository.ts
  backend/src/services/authService.ts
  frontend/src/containers/ProfilePopup/sagas.ts
  workspace.code-workspace
Labels: bug

#44 Feature 404 page
  frontend/src/containers/Routing/index.tsx
  frontend/src/scenes/Auth/components/SignUp/index.tsx
  frontend/src/scenes/Auth/components/SignUp/styles.module.scss
  frontend/src/scenes/Auth/containers/index.tsx
  frontend/src/scenes/NotFound/components/NotFound/index.tsx
  frontend/src/scenes/NotFound/components/NotFound/styles.module.scss
  frontend/src/scenes/Routing/index.tsx
Labels: enhancement

#62 change logo
  frontend/src/components/Header/index.tsx
  frontend/src/images/Logo.svg
  frontend/src/images/retool-logo.png
  frontend/src/scenes/Auth/components/SignIn/index.tsx
  frontend/src/scenes/Auth/components/SignUp/index.tsx
Labels: enhancement

#63 Feature/table component
  frontend/package.json
  frontend/src/components/TableComponent/index.tsx
  frontend/src/components/TableComponent/styles.module.scss
  frontend/src/components/TableComponentCell/index.tsx
  frontend/src/components/TableComponentHeaderCell/index.tsx
Labels: enhancement

#67 Change confirm message
  frontend/src/common/models/formik/ValidationSchemas.ts
Labels: bug

#68 Feature/query functional
  backend/src/api/routes/index.ts
  backend/src/api/routes/queriesRoute.ts
  backend/src/common/models/query/ICreateQuery.ts
  backend/src/common/models/query/ITransportedQuery.ts
  backend/src/common/models/query/IUpdateQuery.ts
  backend/src/common/models/query/Trigger.ts
  backend/src/data/entities/Trigger.ts
  backend/src/data/migrations/1616006482033-addSuccessToPrimaryKey.ts
  backend/src/data/repositories/queryRepository.ts
  backend/src/data/repositories/triggerRepository.ts
  backend/src/services/queryService.ts
  frontend/src/common/helpers/arrayHelper.ts
  frontend/src/common/models/apps/querys.ts
  frontend/src/common/models/formik/ValidationSchemas.ts
  frontend/src/common/models/query/ICreateQuery.ts
  frontend/src/common/models/query/IDeleteQuery.ts
  frontend/src/common/models/query/IQueryState.ts
  frontend/src/common/models/query/ITrigger.ts
  frontend/src/common/models/query/IUpdateQuery.ts
  frontend/src/common/models/query/IWaitingQuery.ts
  frontend/src/common/models/store/IAppState.ts
  frontend/src/components/ProfilePopupInfo/ProfilePopupInfo.tsx
  frontend/src/components/ProfilePopupInfo/styles.module.scss
  frontend/src/reducers/appsRoot.ts
  frontend/src/reducers/queries.ts
  frontend/src/reducers/root.ts
  frontend/src/sagas/applicationRootSaga.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Apps/containers/UpdateApp/index.tsx
  frontend/src/scenes/Apps/index.tsx
  frontend/src/scenes/Apps/sagas/index.ts
  frontend/src/scenes/Auth/components/SignUp/index.tsx
  frontend/src/scenes/Settings/containers/Users/index.tsx
  frontend/src/scenes/constructor/components/ModalWindow/index.tsx
  frontend/src/scenes/constructor/components/QueryBlock/index.tsx
  frontend/src/scenes/constructor/components/QueryBlock/style.module.scss
  frontend/src/scenes/constructor/components/closeSpanComponent/index.tsx
  frontend/src/scenes/constructor/components/closeSpanComponent/style.module.scss
  frontend/src/scenes/constructor/components/queriesList/index.tsx
  frontend/src/scenes/constructor/components/queriesList/style.module.scss
  frontend/src/scenes/constructor/components/triggerBlock/index.tsx
  frontend/src/scenes/constructor/components/triggerBlockUnSuccess/index.tsx
  frontend/src/scenes/constructor/components/triggerList/index.tsx
  frontend/src/scenes/constructor/components/triggerList/style.module.scss
  frontend/src/scenes/constructor/components/triggerListUnSuccess/index.tsx
  frontend/src/scenes/constructor/components/triggerListUnSuccess/style.module.scss
  frontend/src/scenes/constructor/containers/index.tsx
  frontend/src/scenes/constructor/containers/style.module.scss
  frontend/src/scenes/constructor/routines/index.ts
  frontend/src/scenes/constructor/sagas/index.ts
  frontend/src/services/queryService.tsx
Labels: enhancement

#72 Fix/resource page style
  frontend/src/components/ProfilePopupInfo/ProfilePopupInfo.tsx
  frontend/src/components/ProfilePopupInfo/styles.module.scss
  frontend/src/scenes/Resources/containers/CreateEditResource/index.tsx
  frontend/src/scenes/Resources/containers/CreateEditResource/styles.module.scss
Labels: bug

#74 Patch/edite page
  backend/src/common/models/query/IUpdateQuery.ts
  backend/src/services/queryService.ts
  frontend/package.json
  frontend/src/common/enums/Routes.ts
  frontend/src/common/models/query/IQueryState.ts
  frontend/src/common/models/query/IWaitingQuery.ts
  frontend/src/reducers/apps.ts
  frontend/src/reducers/queries.ts
  frontend/src/scenes/Apps/components/AppItem/index.tsx
  frontend/src/scenes/Apps/components/Editor/index.tsx
  frontend/src/scenes/Apps/containers/AppEditor/index.tsx
  frontend/src/scenes/Apps/containers/AppEditor/styles.module.scss
  frontend/src/scenes/Apps/routines/index.ts
  frontend/src/scenes/Resources/sagas/index.ts
  frontend/src/scenes/constructor/components/ModalWindow/index.tsx
  frontend/src/scenes/constructor/components/QueryBlock/index.tsx
  frontend/src/scenes/constructor/components/ResourceBlock/index.tsx
  frontend/src/scenes/constructor/components/ResourceList/index.tsx
  frontend/src/scenes/constructor/components/queriesList/index.tsx
  frontend/src/scenes/constructor/containers/index.tsx
  frontend/src/scenes/constructor/containers/style.module.scss
  frontend/src/scenes/constructor/routines/index.ts
Labels: enhancement

#82 add delete confirmation modal
  frontend/src/scenes/Apps/components/AppItem/index.tsx
  frontend/src/scenes/Apps/components/DeleteModal/index.tsx
  frontend/src/scenes/Resources/components/DeleteModal/index.tsx
  frontend/src/scenes/Resources/components/ResourceItem/index.tsx
Labels: enhancement

#78 Feature forget password(fixed and tested)
  backend/package.json
  backend/src/api/middlewares/jwtMiddleware.ts
  backend/src/api/middlewares/userMiddleware.ts
  backend/src/api/routes/authRoute.ts
  backend/src/common/constants/http.ts
  backend/src/common/constants/regexp.ts
  backend/src/common/helpers/cryptoHelper.ts
  backend/src/common/helpers/mailHelper.ts
  backend/src/common/models/forgetPassword/forgotPasswordSchema.ts
  backend/src/common/models/mail/IMail.ts
  backend/src/common/models/mail/IResetPasswordMessage.ts
  backend/src/common/models/user/IForgotPasswordUser.ts
  backend/src/config/passportConfig.ts
  backend/src/config/routesWhiteListConfig.ts
  backend/src/data/repositories/refreshTokenRepository.ts
  backend/src/data/repositories/userOrganizationRepository.ts
  backend/src/data/repositories/userRepository.ts
  backend/src/services/applicationService.ts
  backend/src/services/authService.ts
  backend/src/services/mailService.ts
  backend/src/services/organizationService.ts
  backend/src/services/resourceService.ts
  backend/src/services/userOrganizationService.ts
  frontend/package.json
  frontend/src/common/enums/Routes.ts
  frontend/src/common/models/auth/AuthServerResponse.ts
  frontend/src/common/models/auth/IForgotPasswordInput.ts
  frontend/src/common/models/auth/IResetPassword.ts
  frontend/src/common/models/auth/IResetPasswordCallback.ts
  frontend/src/common/models/auth/IResetPasswordInput.ts
  frontend/src/common/models/auth/TForgotPassword.ts
  frontend/src/common/models/auth/THandleForgotPassword.ts
  frontend/src/common/models/auth/THandleResetPassword.ts
  frontend/src/common/models/formik/ValidationSchemas.ts
  frontend/src/common/models/formik/forgotPasswordSchema.ts
  frontend/src/common/models/formik/resetPasswordSchema.ts
  frontend/src/reducers/user.ts
  frontend/src/scenes/Auth/components/ForgotPassword/index.tsx
  frontend/src/scenes/Auth/components/ForgotPassword/styles.module.scss
  frontend/src/scenes/Auth/components/ResetPassword/index.tsx
  frontend/src/scenes/Auth/components/ResetPassword/styles.module.scss
  frontend/src/scenes/Auth/components/SignIn/index.tsx
  frontend/src/scenes/Auth/containers/index.tsx
  frontend/src/scenes/Auth/routines/index.ts
  frontend/src/scenes/Auth/sagas/index.ts
  frontend/src/services/authService.tsx
Labels: bug

#83 Feature/connect query to table
  backend/src/api/routes/queriesRoute.ts
  backend/src/common/models/queries/ICreateQuery.ts
  backend/src/common/models/query/ICreateQuery.ts
  backend/src/data/repositories/triggerRepository.ts
  backend/src/services/queryService.ts
  backend/src/services/triggerService.ts
  frontend/src/common/helpers/arrayHelper.ts
  frontend/src/common/models/apps/querys.ts
  frontend/src/common/models/queries/ICreateQuery.ts
  frontend/src/common/models/queries/IQuery.ts
  frontend/src/common/models/query/IQueryState.ts
  frontend/src/common/models/query/IRunQuery.ts
  frontend/src/reducers/queries.ts
  frontend/src/scenes/Resources/components/TableContainer/index.tsx
  frontend/src/scenes/constructor/components/ModalWindow/confirm.tsx
  frontend/src/scenes/constructor/components/ModalWindow/queryResult.tsx
  frontend/src/scenes/constructor/containers/index.tsx
  frontend/src/scenes/constructor/containers/style.module.scss
  frontend/src/scenes/constructor/routines/index.ts
  frontend/src/scenes/constructor/sagas/index.ts
  frontend/src/services/queryService.tsx
Labels: enhancement

#88 Fix/change actions
  frontend/src/scenes/Apps/components/AppItem/index.tsx
  frontend/src/scenes/Apps/components/AppItem/styles.module.scss
  frontend/src/scenes/Resources/components/ResourceItem/index.tsx
  frontend/src/scenes/Resources/components/ResourceItem/styles.module.scss
Labels: bug

#89 Fix/highlight options
  frontend/src/components/ProfilePopupInfo/ProfilePopupInfo.tsx
  frontend/src/components/ProfilePopupInfo/styles.module.scss
Labels: bug

#91 Patch/bagger
  frontend/src/reducers/queries.ts
  frontend/src/scenes/Apps/containers/AppEditor/index.tsx
  frontend/src/scenes/Apps/containers/AppEditor/styles.module.scss
  frontend/src/scenes/Resources/containers/CreateEditResource/index.tsx
  frontend/src/scenes/Resources/containers/CreateEditResource/styles.module.scss
  frontend/src/scenes/constructor/containers/index.tsx
  frontend/src/scenes/constructor/containers/style.module.scss
Labels: bug

#98 Add cascade delete component (button, input, text, table)
  backend/src/data/entities/Button.ts
  backend/src/data/entities/Input.ts
  backend/src/data/entities/Table.ts
  backend/src/data/entities/Text.ts
  backend/src/data/migrations/1616611938002-addCascadeDeleteComponent.ts
Labels: enhancement

#97 Feature/table
  backend/package.json
  backend/src/common/models/editor/IResponse.ts
  backend/src/common/models/editor/ITable.ts
  backend/src/data/migrations/1616600253019-dropnull.ts
  backend/src/data/repositories/tableRepository.ts
  backend/src/services/editorService.ts
  frontend/package.json
  frontend/src/common/models/editor/IButton.ts
  frontend/src/common/models/editor/IDropItem.ts
  frontend/src/common/models/editor/IInputText.ts
  frontend/src/common/models/editor/ITable.ts
  frontend/src/scenes/Apps/components/DropArea/index.tsx
  frontend/src/scenes/Apps/components/DropAreaItem/index.tsx
  frontend/src/scenes/Apps/components/Editor/index.tsx
  frontend/src/scenes/Apps/components/Inspect/index.tsx
  frontend/src/scenes/Apps/components/Item/index.tsx
  frontend/src/scenes/Apps/components/queryBlock/index.tsx
  frontend/src/scenes/Apps/components/queryBlock/styles.module.scss
  frontend/src/scenes/Apps/components/queryList/index.tsx
  frontend/src/scenes/Apps/components/queryList/styles.module.scss
  frontend/src/scenes/Apps/components/tableDATA/index.tsx
  frontend/src/scenes/Apps/routines/index.ts
Labels: enhancement

#101 Feature/input component
  backend/package.json
  backend/src/common/models/editor/IInputText.ts
  backend/src/common/models/editor/input/ICreateInput.ts
  backend/src/common/models/editor/input/IUpdateInput.ts
  backend/src/common/models/queries/ICreateQuery.ts
  backend/src/common/models/query/ICreateQuery.ts
  backend/src/common/models/query/ITransportedQuery.ts
  backend/src/common/models/query/IUpdateQuery.ts
  backend/src/data/entities/Input.ts
  backend/src/data/entities/Query.ts
  backend/src/data/migrations/1616542595399-addInputQueryId.ts
  backend/src/data/migrations/1616606996441-not auto run.ts
  backend/src/data/repositories/inputRepository.ts
  backend/src/services/editorService.ts
  backend/src/services/queryService.ts
  frontend/src/common/models/apps/querys.ts
  frontend/src/common/models/editor/IEditorState.ts
  frontend/src/common/models/editor/IInputText.ts
  frontend/src/common/models/editor/ILocal.ts
  frontend/src/common/models/editor/input/IAddInput.ts
  frontend/src/common/models/queries/ICreateQuery.ts
  frontend/src/common/models/queries/IQuery.ts
  frontend/src/common/models/query/ICreateQuery.ts
  frontend/src/common/models/query/IQueryState.ts
  frontend/src/common/models/query/IWaitingQuery.ts
  frontend/src/reducers/appsEditor.ts
  frontend/src/reducers/queries.ts
  frontend/src/scenes/Apps/components/DropArea/index.tsx
  frontend/src/scenes/Apps/components/Inspect/index.tsx
  frontend/src/scenes/Apps/components/Item/index.tsx
  frontend/src/scenes/Apps/containers/InputComponent/index.tsx
  frontend/src/scenes/Apps/routines/index.ts
  frontend/src/scenes/Apps/sagas/index.ts
  frontend/src/scenes/constructor/components/ModalWindow/index.tsx
  frontend/src/scenes/constructor/components/QueryBlock/index.tsx
  frontend/src/scenes/constructor/components/queriesList/index.tsx
  frontend/src/scenes/constructor/components/triggerBlock/index.tsx
  frontend/src/scenes/constructor/components/triggerBlockUnSuccess/index.tsx
  frontend/src/scenes/constructor/components/triggerList/index.tsx
  frontend/src/scenes/constructor/components/triggerListUnSuccess/index.tsx
  frontend/src/scenes/constructor/containers/index.tsx
  frontend/src/services/applicationService.tsx
  frontend/src/services/queryService.tsx
Labels: enhancement

#102 fix
  frontend/src/common/models/editor/IButton.ts
  frontend/src/common/models/editor/ITable.ts
  frontend/src/reducers/appsEditor.ts
  frontend/src/scenes/Apps/components/DropArea/index.tsx
  frontend/src/scenes/Apps/components/Editor/index.tsx
  frontend/src/scenes/Apps/components/queryList/index.tsx
  frontend/src/scenes/Apps/components/tableDATA/index.tsx
Labels: bug

#106 add button functional
  frontend/src/scenes/Apps/components/ButtonComponent/index.tsx
  frontend/src/scenes/Apps/components/DropArea/index.tsx
  frontend/src/scenes/Apps/components/Editor/index.tsx
Labels: enhancement

#110 change text
  frontend/src/scenes/Apps/components/DeleteModal/index.tsx
  frontend/src/scenes/Resources/components/DeleteModal/index.tsx
Labels: bug

#116 fix table
  frontend/src/components/TableComponent/index.tsx
  frontend/src/scenes/Apps/components/DropArea/index.tsx
  frontend/src/scenes/Apps/components/Item/index.tsx
  frontend/src/scenes/Apps/components/tableDATA/index.tsx
  frontend/src/scenes/Resources/containers/CreateEditResource/styles.module.scss
  frontend/src/scenes/constructor/components/ModalWindow/queryResult.tsx
  frontend/src/scenes/constructor/containers/index.tsx
  frontend/src/scenes/constructor/sagas/index.ts
Labels: bug

#122 fix reducer
  frontend/src/scenes/Apps/components/Editor/index.tsx
  frontend/src/scenes/Apps/containers/AppEditor/index.tsx
  frontend/src/scenes/Resources/containers/CreateEditResource/styles.module.scss
  frontend/src/scenes/constructor/containers/index.tsx
Labels: bug

#129 Patch/lastFix
  frontend/src/reducers/queries.ts
  frontend/src/scenes/Apps/components/DropArea/index.tsx
  frontend/src/scenes/Apps/components/Editor/index.tsx
  frontend/src/scenes/Apps/containers/AppEditor/index.tsx
  frontend/src/scenes/Apps/routines/index.ts
  frontend/src/scenes/Resources/sagas/index.ts
  frontend/src/scenes/constructor/routines/index.ts
  frontend/src/scenes/constructor/sagas/index.ts
Labels: bug, enhancement
